### PR TITLE
[WIP] A Fresh Start

### PR DESCRIPTION
**Pull request by Deon**

### CODE REVIEW

**Comment by Kong-Artist** [comment]
Bye Felicia

**Comment by Deon** [comment]
@icechen1 PTAL

**Comment by Deon** [comment]
Closes #3

**Comment by icechen1** [comment]
Looks good to me, should we update the readme on how to get started (if it changed from before)

**Comment by Deon** [comment]
Yeah I'll update the Readme

**Comment by icechen1** [comment]
Clear and concise 👍

**Pull request merged**
